sudo: false

language: node_js
node_js:
  - "4.0"
  - "5.0"
  - "6.0"

branches:
  only:
    - master
    - travis-fix

cache:
  directories:
    - node_modules

before_install:
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm prune
  - npm install

notifications:
  email: false
