sudo: false

language: node_js
node_js:
  - "4.0"
  - "5.0"
  - "6.0"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

notifications:
  email: false

install:
  - npm prune
  - npm install
